/*CREATE TABLE OPINIONCHARTS (
  id BIGSERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  opinions TEXT[] NOT NULL,
);*/

CREATE TABLE OPINIONSESSIONS (
  id SERIAL PRIMARY KEY,
  session_id BIGINT NOT NULL,
  opinions BIGINT NOT NULL,
);

